### PR TITLE
Search fix

### PR DESCRIPTION
**Pull request by amanji**
* Fixes an issue in the search autocomplete where the autocomplete list click handler returns early if there is only one entry in the autocomplete list.
* Updates styling on search bar to better align with wider application

### CODE REVIEW

**Review by swcurran — APPROVED** [review]

**Comment by swcurran** [comment]
Please post to test ASAP, and we'll go to Prod right after.  Heads up @WadeBarnes / @wadeking98 .

**Comment by WadeBarnes** [comment]
@swcurran, Deployed.

**Comment by swcurran** [comment]
Verified that it works on Dev and Test.  I had a caching issue on Test before realizing it was working. Please deploy to prod.

Thanks!

**Comment by WadeBarnes** [comment]
[bcgov/orgbook-bc-client v1.0.5](https://github.com/bcgov/orgbook-bc-client/releases/v1.0.5) has been deployed to `prod`.

**Pull request merged**
