### PR TITLE
added search help popup

### PR DESCRIPTION
**Pull request by wadeking98**
Added UI components and functionality to instruct users on how to search. Here are the mobile and desktop views for the UI.
## Desktop:
image  

## Mobile:
image

The popup uses the wording in #140 

Signed-off-by: wadeking98 <wkingnumber2@gmail.com>

### CODE REVIEW

**Review by swcurran — APPROVED** [review]

**Comment by swcurran** [comment]
What is the status of getting the UI changes you have done to production?  What is the flow for those happening?

**Comment by wadeking98** [comment]
@swcurran I believe once all the priority issues are cleared, Wade Barnes will create a new release and deploy it to test. After all the testing is completed in test, it will be moved to prod

**Comment by WadeBarnes** [comment]
Correct, I was waiting for the rest of these to be knocked off first; https://github.com/bcgov/orgbook-bc-client/issues?q=is%3Aissue+is%3Aopen+label%3A%22priority+for+cleanup%22

**Comment by swcurran** [comment]
How much extra work is it to push them as they are completed?  I was expecting/would prefer them to go as they were done. Not the end of the world, but all things being equal, the sooner the better.

**Comment by WadeBarnes** [comment]
I'll push what we have to `test`.  Someone should go through each issue and give it a good test.

**Comment by wadeking98** [comment]
issue #113 is waiting on the meeting with the GDX folks
issue #74 is waiting on Dwayne Gordon to get the wording in place
issue #76 is waiting on this PR to be reviewed and merged: https://github.com/bcgov/orgbook-bc-client/pull/139

**Comment by WadeBarnes** [comment]
@swcurran, The latest code is now in `test`.

**Comment by swcurran** [comment]
Testing.  A link on the results page should also be there to the same text.  It should be beside the "xxx result(s)" line.

image

Try to see of you can make "Not finding what you want?" look good, or just use the same "(I)" icon as on the main page.

**Pull request merged**
