### PR TITLE
Remove use of verification from credential details

### LINKED ISSUE #239: UI updates for displaying credentials issued on unsupported/retired ledgers.
OrgBook displays a `Credential verified` badge/link for credentials issued to a registered company that are current (not expired/replaced):
Image
When following the link, a call to the `/verify` endpoint is performed: this triggers an internal proof-request that is used to validate the credential and generate the verification page (example: https://orgbook.gov.bc.ca/entity/FM0357337/credential/5785650).

With the imminent shutdown of Sovrin and the resulting move of BC Gov issuers from Sovrin to CANdy, all credentials issued on MainNet will become unverifiable as soon as the ledger the issuers were rooted on ceases to exist.

Updates to the UI are required in order to avoid user confusion when browsing records, and in particular:
- Wording should be updated to reflect that the credential is not "verified", but may still be current
- The self-verification step should be skipped, since it is not really providing added value (and it will not be possible for credentials issued on an retired ledger)
- The verification page should still display the credential claims, but will not display the proof payload

**Note:** for credential types other than AnonCreds (such as W3C) the `verify` endpoint might be in use to extract the claims to be displayed in the UI. Functionality for this type of credentials must be retained.

### PR DESCRIPTION
**Pull request by Gavinok**
This PR resolves #239

No calls to `/verify` will now be made and the mentions of verification have been removed.

Here is a revoked credential

This is a non revoked credential

### CODE REVIEW

**Review by amanji — CHANGES_REQUESTED** [review]
We need to keep the panels for `rawData` and "vc_di" types. You can remaining the panel logic for `proofValues` (any if-else blocks, etc.).

**Comment by Gavinok** [comment]
Since `proofValues` is no longer an option available (it requires the `/verify` endpoint) I have removed it but still restored the rawData field

**Review by esune — APPROVED** [review]
LGTM 👍🏻 

@amanji I think your comment was addressed, if you confirm we can merge

**Comment by esune** [comment]
Tested and UI works as expected

**Review by esune — APPROVED** [review]

**Pull request merged**
