### PR TITLE
added simple advanced search page

### LINKED ISSUE #70: Regression -- being able to search for all credentials of a given type
In the Old OrgBook UI, the advanced search feature has commonly used in demos to find a company with a specific type of credential.  This is probably the only use of the "advanced search".  Not particularly useful, but great for demos when you don't know the names of companies that have a specific type of credential.  We (and especially @watkinspd  and @jljordan42 ) would like that "Show me a list of companies with a given credential".

One idea for doing that, might be on this screen (image below), where we show all the credential types. Could the credential types be a link or perhaps have a "magnifying glass" search icon beside them that when clicked went to the search screen showing a list of that credential type. 

Open to other ideas of how to get this feature back.  Will it screw up the new search screen (because its using a different API or search parameters), or can we get to the search screen in that context?

image

### PR DESCRIPTION
**Pull request by wadeking98**
Added ability to search by credential type
Resolves: #70  
Signed-off-by: wadeking98 <wkingnumber2@gmail.com>

### CODE REVIEW

**Comment by amanji** [comment]
@swcurran Is this the intended implementation? I recall the discussion being something around linking to search results by type from the Data Types (About) section. I'm of the view that if we want to add a separate advanced search feature, perhaps we should iterate on the current search feature. Thoughts? What about you @wadeking98?

**Comment by WadeBarnes** [comment]
@amanji, Based on this comment I would say this is not the intended implementation; https://github.com/bcgov/orgbook-bc-client/issues/70#issuecomment-1020669080

> @swcurran Is this the intended implementation? I recall the discussion being something around linking to search results by type from the Data Types (About) section. I'm of the view that if we want to add a separate advanced search feature, perhaps we should iterate on the current search feature. Thoughts? What about you @wadeking98?

**Comment by swcurran** [comment]
See my notes on the issue #70 -- we don't want to have this implemented in this way.  We don't really want an "Advanced Search" at all, unless it provides features that are more like one would expect in an advanced search. This is definitely not that.

**Comment by amanji** [comment]
Ah, I should have read through the issue discussion. I agree with @swcurran on his comments. The link-based approach is much cleaner for now until we iterate on the existing search bar.

**Comment by wadeking98** [comment]
@swcurran @amanji @WadeBarnes I've refactored the changes now and made it in line with Stephen's suggestion of having links on the page

**Review by swcurran — COMMENTED** [review]
Could you please provide a screenshot of what it looks like?  I'm not set up to run the app locally.

Thanks!

**Review by amanji — APPROVED** [review]

**Comment by wadeking98** [comment]
@swcurran here is what the page looks like:
image

**Comment by swcurran** [comment]
How about one more tweak.  Title that "Credential Search by Type" vs. "Credentials"?  I think that makes it a little clearer...

**Pull request merged**
