### PR TITLE
changed format for relationship links

### LINKED ISSUE #149: Remove larger text and bold on "Relationship" links
For example, on: https://test.orgbook.gov.bc.ca/entity/FM0239928b

The link for the owning entity "WESTCOAST HOBBIES 4 U LTD." is in (I think) a larger font and bold. I don't think that is needed.

I suggest also making it a bulleted (unordered) list vs. just a line of text.

When done locally, please add screenshots before PRing this change.

Thanks

### PR DESCRIPTION
**Pull request by wadeking98**
## Preview (`Does business as` relationship type): 
image  

## Preview (`Owned by` relationship type):
image
image

Resolves: #149 
Signed-off-by: wadeking98 <wkingnumber2@gmail.com>

### CODE REVIEW

**Review by swcurran — CHANGES_REQUESTED** [review]
LGTM -- please fix the merge conflicts.

**Review by swcurran — APPROVED** [review]

**Comment by swcurran** [comment]
@WadeBarnes Ready for another deployment to test for final checkout before promotion.

**Comment by WadeBarnes** [comment]
@swcurran, The latest code has been deployed to `test`.

**Comment by swcurran** [comment]
Small bug found on Test -- there is an extra space at the start of the link for an "owned by" organization. Let's get that fixed please, @wadeking98 

image

**Pull request merged**
