### PR TITLE
save scroll position for entity result

### LINKED ISSUE #94: Navigating to one link and then back again looses your place on the first page
Example: https://frontend-v2-prod.apps.silver.devops.gov.bc.ca/entity/BC0928747

Locate a credential in the list and click on the **Credential verified** link to view the credential:
image

image

Now click the link to go back to the company detail screen.  You end up at the top of the page and the credential you had opened is now closed, so you have completely lost your place on the page.

image

### PR DESCRIPTION
**Pull request by wadeking98**
Resolves: #94 
- save scroll position of pages before leaving
- restore page position for entity result view
Signed-off-by: wadeking98 <wkingnumber2@gmail.com>

### CODE REVIEW

**Review by amanji — CHANGES_REQUESTED** [review]
I don't think storing state in the route config is the right choice here. Perhaps Vuex?

**Comment by wadeking98** [comment]
> I don't think storing state in the route config is the right choice here. Perhaps Vuex?

But wouldn't the state be cleared when navigating between different views?

**Comment by amanji** [comment]
You can confirm if that's case. I suggest to try installing [Vue Devtools](https://devtools.vuejs.org) which allows you to see Vuex state changes across the application as you interact with it. Vuex is designed to store global application state that is persisted until a mutation is called to update that state. With that being said the route config on OrgBook is merely there to specify the application routes, it's not meant to have any application state.

**Review by amanji — APPROVED** [review]
Will pass this through for now, but this could be generally useful for keeping scroll position in all last visited routes. Wonder if we can look at as way to generalize this further?

**Pull request merged**
