### PR TITLE
feat: add other entity types

### PR DESCRIPTION
**Pull request by amanji**

### CODE REVIEW

**Comment by swcurran** [comment]
Where did this change come from?  Presumably BC Registries?

**Comment by swcurran** [comment]
And should it be “Associations” vs. “Association”?  It sounds like a single entity, which is what threw me off.

**Comment by WadeBarnes** [comment]
@amanji, Ping me when this is ready to go.

**Comment by amanji** [comment]
Ready to merge. @swcurran I've taken the description directly from BC Registries.

**Review by WadeBarnes — APPROVED** [review]

**Pull request merged**
