### PR TITLE
Fix UI issues in main search view

### PR DESCRIPTION
**Pull request by esune**
The main changes are in `SearchHome.vue`: the use of `src` and `srcset` seems to have been confusing browsers and causing the image to not be loaded at all - including the container component.

Other changes are updating node image in devcontainer and a couple of tweaks/clean-up items I did while troubleshooting.

### CODE REVIEW

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
With the changes you made to `.devcontainer/devcontainer.json`, `.devcontainer/Dockerfile` is not used anymore.

**Comment by esune** [comment]
> With the changes you made to `.devcontainer/devcontainer.json`, `.devcontainer/Dockerfile` is not used anymore.

Should be fixed! I was working across two machines and didn't realize I overrode the changes in the one I used to push last.

**Review by WadeBarnes — APPROVED** [review]

**Comment by loneil** [comment]
changed vite config to `https://dev.orgbook.gov.bc.ca`
`npm ci`
`npm run serve`

image

For docker just hardcoded the quickload api call to dev orgbook (didn't want to spin up von/vcr etc)
`./manage build ./manage start` worked

I get an error loading the devcontainer through on my local:
image

Looks like this got merged as I was testing but I think the Vue image part is all good, as is the package-lock situation with the rebuild

**Comment by WadeBarnes** [comment]
Yeah, sorry.  The client portion was working.  So I though I'd get it deployed.

**Comment by loneil** [comment]
Yeah no prob, the problem with the client app looks fixed so good to merge, might just be a windows devcontainer issue or something with my setup

**Comment by esune** [comment]
I just rebuilt the devcontainer and it is still working for me so I think/hope it is a temporary resolution error

**Pull request merged**
